### ISSUE TITLE
How to alleviate overfitting

### ISSUE THREAD

**Issue by Shuaizhang7** [fudan-zvg/4d-gaussian-splatting#46] opened 2024-08-31 14:52 UTC
Thank you for your great work. When I used your code to process my own dataset, I encountered serious overfitting problems. What methods can be used to alleviate the overfitting problem, or what parameters should I adjust to alleviate this problem?

**Comment by Alexander0Yang** [comment] 2024-09-02 09:20
Hi @Shuaizhang7, 
We also noticed that in some under-constrained scenes, our method is prone to overfitting due to lacking of smooth motion prior inherent in the deformation field. According to our experience, increasing the interval of densification sometimes can alleviate overfitting. Controlling undesired motion also might be useful, it could be achieved by decreasing the learning rates for scaling and rotation to slow down the learning of motion derived from the 4D rotation, or directly imposing some regularization: such as encouraging larger covariance in the time dimension; applying rigid prior for neighboring 4D Gaussians; or penalizing differences between the left and right quaternions.

**Comment by Shuaizhang7** [comment] 2024-09-02 09:27
Thank you very much for your reply. After I set rot_4d to False, the results were greatly improved. I would like to ask what this parameter means? Does it mean that 4D Gaussains degenerate into 3D Gaussian? My gaussian_dim parameter is still set to 4.

**Comment by Alexander0Yang** [comment] 2024-09-02 13:51
Once the rot_4d is set to False, the covariance between time and other spatial dimensions will be fixed to zero. Imposing large enough penalty on the differences between the left and right quaternions to make them totally same can also achieve the similar effect. This means that there are no longer any motions induced by 4D rotation, only a series of 3D Gaussians that appear and disappear over time. (Compared to true 3D Gaussian, their opacity still varies with time, so the statement of “degenerate to a 3D Gaussian” in my first commet is not very precise). By the way, there are many types of possible overfitting of 4D Gaussian. In some cases, this setting (disenabling rot_4d) would limit the effective use of multi-view supervision due to the its inability to model dynamics. But it could be helpful if the overfitting is mainly caused by the undesired motions.

**Comment by Shuaizhang7** [comment] 2024-09-02 14:00
Thanks for your reply, I think it fits my situation very well. I am mainly dealing with medical 4D DSA data, where objects do not move (vessels remain stationary), only opacity changes. Therefore, when I set rot_4d to True, I get very severe overfitting, while when I set rot_4d to False, I get good results.

**Closed** 2024-09-04 02:50 UTC
